// vue/src/views/video/demo/live.vue
<script>
import Reflv from "../components/reflv";
export default {
  components: {
    Reflv
  },
  data() {
    return {
      url: "http:xxxxx/flv.js"
    };
  },
  render() {
    let { url } = this;
    return (
      <Reflv
        url={url}
        type="flv"
        isLive
        hasAudio
        hasVideo
        cors
        config={{
          enableWorker: true,
          enableStashBuffer: false,
          stashInitialSize: 128
        }}
      />
    );
  }
  // computed: {},
  // watch: {},
  // methods: {},
  // created() {},
  // mounted() {},
  // beforeCreate() {},
  // beforeMount() {},
  // beforeUpdate() {},
  // updated() {},
  // beforeDestroy() {},
  // destroyed() {},
  // activated() {}
};
</script>
<style scoped>
</style>

// react/src/pages/video/live.js
import React, { PureComponent } from 'react';
import Reflv from './components/Reflv';

export class Live extends PureComponent {

    render () {
        return (
            <Reflv
                url={"http://192.168.1.115:7001/live/movie.flv"}
                type="flv"
                isLive
                cors
                config={{
                    enableWorker: true,
                    enableStashBuffer: false,
                    stashInitialSize: 128,
                }}
            />
        )
    }
}
